sudo ejabberdctl register director localhost directoruser
sudo ejabberdctl register punch localhost punchuser
sudo ejabberdctl register judy localhost judyuser
sudo ejabberdctl register joey localhost joeyuser
sudo ejabberdctl register croc localhost crocuser
sudo ejabberdctl register baby localhost babyuser
sudo ejabberdctl register police localhost policeuser
sudo ejabberdctl register anim localhost animuser
sudo ejabberdctl register log localhost loguser
